services:
  - type: web
    name: joinlah-bot
    env: node
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: NODE_VERSION
        value: 22.12.0
